name: fooling around

on:
  push:
    branches:
      - master

jobs:
  runs-on: ubuntu-latest
  useless_job:
    steps:
    - uses: docker://alpine:3.8
    - name: some figlet thing
      run: |
        apk update && apk upgrade \
        apk add figlet \
        figlet holy fig
